language: node_js
node_js:
  - 12
  - 11
  - 10
  - node

os: 
  - osx
  - windows
  - linux
dist: xenial  

before_script:
  - npm install
  - npx lerna bootstrap

script:
  - npx lerna run --stream test:ci

notifications:
  email: false
  slack:
    rooms:
      - assafsapir:Tv6pbfSHv3a68VaCMwfAoJIH#story-line

branches:
  only:
  - master