language: node_js
node_js:
  - 12
  - 11
  - 10
  - node

os: 
  - osx
  - linux
dist: xenial  

before_script:
  - npm install
  - lerna exec npm install

script:
  - lerna run test:ci

notifications:
  email: false
  slack:
    rooms:
      - assafsapir:Tv6pbfSHv3a68VaCMwfAoJIH#story-line

branches:
  only:
  - master