language: node_js
node_js:
  - 12
  - 11
  - 10
  - node

os: 
  - osx
  - linux
dist: xenial  

before_script:
  - cd api
  - npm install
  - npm run build

script:
  - npm run test:ci
  - cd ..
  - cd ui
  - npm install
  - npm run build
  - npm run test:ci

notifications:
  email: false
  slack:
    rooms:
      - assafsapir:Tv6pbfSHv3a68VaCMwfAoJIH#story-line

branches:
  only:
  - master