name: docker-build

on:
  push:
    branches:
    -  master
  pull_request:
    branches:
    -  master

jobs:
  API:
    name: Build Typescript/Express API
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and run tests
      working-directory: ./api/
      run: npm install --silent && npm test

  UI:
    name: Build React UI
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build and run tests
      working-directory: ./ui/
      run: npm install --silent && npm test

  PUSH_API:
    name: Push API Docker image to GitHub Packages
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set image version based on tag
        run: echo ::set-env name=TAG::$(date +%s)
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: ./api/
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/story-line-api
          tags: ${{ env.TAG }}
          add_git_labels: true

  PUSH_UI:
    name: Push API Docker image to GitHub Packages
    runs-on: ubuntu-latest
    if: success() && github.ref == 'refs/heads/master'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set image version based on tag
        run: echo ::set-env name=TAG::$(date +%s)
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v1
        with:
          path: ./ui/
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/story-line-ui
          tags: ${{ env.TAG }}
          add_git_labels: true
  
